// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9eVVlpmDgoIy5gimNnB5tpddHud6hCG4',
    appId: '1:605480071892:web:75d89fb30c51b1c0f28141',
    messagingSenderId: '605480071892',
    projectId: 'my-travelo-6c57a',
    authDomain: 'my-travelo-6c57a.firebaseapp.com',
    storageBucket: 'my-travelo-6c57a.appspot.com',
    measurementId: 'G-LJ09FMMJ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALENWOOf4CN1RwayjoO542H49QIuEBsR0',
    appId: '1:605480071892:android:f66cd0469fce93a9f28141',
    messagingSenderId: '605480071892',
    projectId: 'my-travelo-6c57a',
    storageBucket: 'my-travelo-6c57a.appspot.com',
  );
}
